### ISSUE TITLE
Host blacklist 

### ISSUE THREAD

**Issue by trimechee** [helloyanis/file-downloader-unleashed#1]
Hello, thank you again fir this amazing addon ! Mercii beaucoup ! 

i have question please, i see the list of websites included in the host blacklist : 

https://github.com/helloyanis/live-stream-downloader-unleashed/commit/8cf10139f2f4ba5fc280e7fe5c502c8136eab6d0

and i see darkfilms.top, darkfilms.cc....

i was thinking only youtube wes blacklistend beacuse the extension can"t donwload dash streams, but it seems the original extension block also some streaming websites., may be after dmca complaints ?....is this true ?

**Comment by helloyanis** [comment]
The web is an open place. The only thing this add-on is doing, is requesting the live stream or media file the same way the browser would when reading the media o the page. Even if there was a DMCA complaint, the magic of open-source is that anyone can make a fork and remove the blocklist like I just did.
On a side note, blocking download on the extension level is a terrible way to protect it, because
1. That gives extra work to the add-on maintainers who do this for free, and
2. The add-on still has full functionality to download stuff, it just will be disabled for specific websites which is really dumb in my opinion
3. Everything here is completely legal, and anyone should be able to download videos and medias for offline viewing!

**Comment by trimechee** [comment]
Great,  thank you :) and about my other question : can you please tell us where your fork stores the temporary files i.e. in which Firefox folder it temporarily stores the parts of the file being downloaded ? I activated the Windiws 10 option which allows us to show hidden files and maybe we could playback temporary files donwloaded by yout fork before the download is finished, the problem i can't see the temporary file downloaded by the extension...beacuse maybe ine the future the extension will implement sequential donwload so we can preview the dowloaded file, thank you !
