### ISSUE TITLE
Another site was added recently to blacklist , no more vital updates of File-downloader-unleashed ?

### ISSUE THREAD

**Issue by trimechee** [helloyanis/file-downloader-unleashed#2]
Hi Mr @helloyanis, how are you?

we hope you are well and fine :)

I noticed there are no more updates of this magnificent exceptional extension, I have tested several extensions and download managers and this extension is the most powerful and efficient in the world, and recently a new site has been added to the blacklist, if in the future my favorite streaming sites are added to the blacklist, the extension will lose its effectiveness and I will no longer be able to download especially since my connection sometimes becomes very weak so the streaming jerks , lag....

we hope please for an update especially since several versions of Live stream downloader have been released since these 4 months, thank you :) and we also hope for a crx version for chromium please to simplify things, my computer crashes breakdown and i use my old eee pc windows os 32 bits and catsxp browser based on chromium is compatible with windows 7 os hence the importance of a crx version for chromium browsers compatible with windows 7 os like supermium,, thanks: )

**Comment by helloyanis** [comment]
Hello!

I have just updated the version with the latest changes. It should appear within a day on the mozilla add-ons store, and update automatically in the following days.

It still does not include the block list, so go download on any website!

I have downgraded the manifest version to v2, to allow for a better experience (I could not get the file count on the add-on icon to appear with manifest v3). Furthermore, some of the features [don't work on firefox yet as of manifest v3](https://github.com/mozilla/web-ext/issues/2532) (although I could get things wrong.

I'm sorry but I will not upload a chrome extension for it, because Chrome is dropping support for manifest v2, which will kill many extensions such as adblockers, [see why this is bad](https://ublockorigin.com/) (scroll down to the section about MV3). It is suspected that Google made this change to be able to show more ads. This is why I will not make add-ons for Chrome. But hey, the source code is there so feel free to make a fork! Open-source is there for this!

Please tell me if you have any more questions.

**Comment by helloyanis** [comment]
It's easy to make your own `.xpi`out of the code! Just download [the contents of the v3 file](https://github.com/helloyanis/file-downloader-unleashed/tree/master/v3), compress it into a zip file and rename the `.zip` to `.xpi`! Or just get the xpi link directly from [the add-ons store
](https://addons.mozilla.org/firefox/downloads/file/4382904/file_downloader_unleashed-0.5.2.xpi)

I'm doing this project for myself so I am not looking for donations. I don't think it would be cool to just make a fork of a full project, change some things and ask for donations.

Mozilla doesn't censor the extension! It has passed review multiple times. And you can already install it from outside of the store, by going to Firefox's debugging page at `about:debugging` > `This firefox` > `Load temporary add-on`.
